### ISSUE TITLE
Deploy to Heroku - Build Error 

### ISSUE THREAD

**Issue by tyrollins** [nicksergeant/snipt#161]
'Deploy to Heroku' button doesn't seem to be working. 

Error:
```

-----> $ python manage.py collectstatic --noinput

       Traceback (most recent call last):

         File "manage.py", line 10, in <module>

           execute_from_command_line(sys.argv)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line

           utility.execute()

         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 316, in execute

           settings.INSTALLED_APPS

         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 53, in __getattr__

           self._setup(name)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup

           self._wrapped = Settings(settings_module)

         File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 97, in __init__

           mod = importlib.import_module(self.SETTINGS_MODULE)

         File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module

           return _bootstrap._gcd_import(name[level:], package, level)

         File "<frozen importlib._bootstrap>", line 978, in _gcd_import

         File "<frozen importlib._bootstrap>", line 961, in _find_and_load

         File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked

         File "<frozen importlib._bootstrap>", line 655, in _load_unlocked

         File "<frozen importlib._bootstrap_external>", line 678, in exec_module

         File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed

         File "/tmp/build_71695ee2e7ef7dd8d0e40587c7dc2b1f/nicksergeant-snipt-817e15a/settings.py", line 17, in <module>

           'http://127.0.0.1:9200/')

       TypeError: 'module' object is not callable

 !     Error while running '$ python manage.py collectstatic --noinput'.

       See traceback above for details.

       You may need to update application code to resolve this error.

       Or, you can disable collectstatic for this application:

          $ heroku config:set DISABLE_COLLECTSTATIC=1

       https://devcenter.heroku.com/articles/django-assets

 !     Push rejected, failed to compile Python app.

 !     Push failed

Build fi
```

**Comment by nicksergeant** [comment]
Hey Tyler! Thanks for the report. Fixed in https://github.com/nicksergeant/snipt/commit/db226eb51192b5919c72ae51352477603d2568c3. 👍
